# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 202) do

  create_table "asistencias", :force => true do |t|
    t.column "usuario_id", :integer,  :null => false
    t.column "charla_id",  :integer,  :null => false
    t.column "created_at", :datetime
  end

  create_table "autores", :force => true do |t|
    t.column "nombre",    :string, :default => "", :null => false
    t.column "apellidos", :string, :default => "", :null => false
    t.column "resumen",   :text,   :default => "", :null => false
    t.column "web",       :string, :default => "", :null => false
    t.column "email",     :string, :default => "", :null => false
    t.column "avatar",    :string
    t.column "notas",     :text
  end

  create_table "autores_charlas", :id => false, :force => true do |t|
    t.column "autor_id",  :integer
    t.column "charla_id", :integer
  end

  create_table "charlas", :force => true do |t|
    t.column "titulo",     :string,   :default => "",    :null => false
    t.column "resumen",    :text,     :default => "",    :null => false
    t.column "fecha",      :datetime
    t.column "duracion",   :integer,  :default => 60,    :null => false
    t.column "sala_id",    :integer
    t.column "aprobada",   :boolean,  :default => false
    t.column "confirmada", :boolean,  :default => false
    t.column "notas",      :text
  end

  create_table "comentarios", :force => true do |t|
    t.column "usuario_id", :integer,                           :null => false
    t.column "charla_id",  :integer,                           :null => false
    t.column "texto",      :text,                              :null => false
    t.column "estado",     :string,   :default => "publicado"
    t.column "created_at", :datetime
    t.column "updated_at", :datetime
  end

  create_table "emails", :force => true do |t|
    t.column "recipients", :text
    t.column "from",       :string
    t.column "subject",    :text
    t.column "sent_on",    :datetime
    t.column "body",       :text
  end

  create_table "perfiles", :force => true do |t|
    t.column "nombre",      :string
    t.column "apellido1",   :string
    t.column "apellido2",   :string
    t.column "telefono",    :string
    t.column "empresa",     :string
    t.column "url_empresa", :string
    t.column "titulo_blog", :string
    t.column "url_blog",    :string
    t.column "cena",        :boolean
    t.column "publico",     :boolean
    t.column "usuario_id",  :integer
    t.column "facturacion", :text
  end

  create_table "roles", :force => true do |t|
    t.column "title", :string
  end

  create_table "roles_usuarios", :id => false, :force => true do |t|
    t.column "role_id",    :integer
    t.column "usuario_id", :integer
  end

  create_table "salas", :force => true do |t|
    t.column "nombre", :string, :default => "", :null => false
  end

  create_table "tarifas", :force => true do |t|
    t.column "importe", :integer
    t.column "actual",  :boolean
  end

  create_table "usuarios", :force => true do |t|
    t.column "login",                     :string
    t.column "email",                     :string
    t.column "crypted_password",          :string,   :limit => 40
    t.column "salt",                      :string,   :limit => 40
    t.column "created_at",                :datetime
    t.column "updated_at",                :datetime
    t.column "remember_token",            :string
    t.column "remember_token_expires_at", :datetime
    t.column "activation_code",           :string,   :limit => 40
    t.column "activated_at",              :datetime
    t.column "password_reset_code",       :string,   :limit => 40
    t.column "password_reseted_at",       :datetime
    t.column "pagado_at",                 :datetime
    t.column "tarifa_id",                 :integer
    t.column "pagado_cena_at",            :datetime
  end

  create_table "votos", :force => true do |t|
    t.column "usuario_id", :integer,  :null => false
    t.column "charla_id",  :integer,  :null => false
    t.column "puntos",     :integer,  :null => false
    t.column "created_at", :datetime
    t.column "updated_at", :datetime
  end

end
